// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWACZ_aRVGWlFeptSK2RvyrDZrLdsFJqk',
    appId: '1:908797335681:web:3e6d464dd055b521605580',
    messagingSenderId: '908797335681',
    projectId: 'fir-meal-99bca',
    authDomain: 'fir-meal-99bca.firebaseapp.com',
    storageBucket: 'fir-meal-99bca.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlhAbiEI8JhJvfDhizO8cWkcoYf4P_qFE',
    appId: '1:908797335681:android:b33f19c6842e5a85605580',
    messagingSenderId: '908797335681',
    projectId: 'fir-meal-99bca',
    storageBucket: 'fir-meal-99bca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLBv1nTWDHj84qm3CqwHR2fR4wpKTDl-s',
    appId: '1:908797335681:ios:c3bfe57b980f193f605580',
    messagingSenderId: '908797335681',
    projectId: 'fir-meal-99bca',
    storageBucket: 'fir-meal-99bca.firebasestorage.app',
    iosClientId: '908797335681-hnes1d8jvknqn347o78889km28habc3i.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLBv1nTWDHj84qm3CqwHR2fR4wpKTDl-s',
    appId: '1:908797335681:ios:c3bfe57b980f193f605580',
    messagingSenderId: '908797335681',
    projectId: 'fir-meal-99bca',
    storageBucket: 'fir-meal-99bca.firebasestorage.app',
    iosClientId: '908797335681-hnes1d8jvknqn347o78889km28habc3i.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDshmrdosC6JCNmcFOvLTYRk7FBFIKKkZw',
    appId: '1:908797335681:web:f8bdd29d2ee25cc3605580',
    messagingSenderId: '908797335681',
    projectId: 'fir-meal-99bca',
    authDomain: 'fir-meal-99bca.firebaseapp.com',
    storageBucket: 'fir-meal-99bca.firebasestorage.app',
  );
}
